services:
  - type: web
    name: lvs-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000